Added Tasks 2.1
UltimateEscanor/EPAM-Tasks pull request #1
Opened 2022-01-05 14:30 UTC by UltimateEscanor

## Overview

Added project Task_1 and tasks: 2.1.1 and 2.1.2

2022-01-24 09:57 UTC, NulleanAndRain commented on Task 2/String/CharacterString.cs
> +        public char[] ToCharArray()
можно использовать метод Array.Clone
public char[] ToCharArray() => (char[])_symbols.Clone();

2022-01-24 10:02 UTC, NulleanAndRain commented on Task 2/String/CharacterString.cs
> +        public bool Equals(CharacterString other)
можно в этот метод добавить сравнение по ссылке чтобы не проходиться по массиву если это один и тот же объект

2022-01-24 10:07 UTC, NulleanAndRain commented on Task 2/String/CharacterString.cs
> +        public bool Contains(char value)
можно сократить до public bool Contains(char value) => FindFirst(value) >= 0;

2022-01-24 10:15 UTC, NulleanAndRain commented on Task 2/String/CharacterString.cs
> +        public static CharacterString ToCharacterString(char[] symbols) => new CharacterString(symbols);
не вижу особого смысла в статическом методе который просто перевызывает публичный конструктор
но если и делать, назвать его стоило FromCharArray

2022-01-24 10:17 UTC, NulleanAndRain commented on Task 2/String/CharacterString.cs
> +        public static bool operator >(CharacterString left, CharacterString right) => left.CompareTo(right) == 1;
не очень очевидно, чего можно ожидать в результате, сравнивая строки с помощью > и <

2022-01-24 10:18 UTC, NulleanAndRain commented on Task 2/String/CharacterString.cs
> +        public static CharacterString operator +(CharacterString left, CharacterString right) => left.Concat(right);
можно добавить сложение с символами и стандартными строками

2022-01-24 10:20 UTC, NulleanAndRain commented on Task 2/Task_2/FigureBuilder.cs
> +                _ => throw new ArgumentOutOfRangeException(nameof(type)),
думаю, здесь лучше бросать исключения типа ArgumentException и стоит писать более подробное описание ошибки

2022-01-24 10:24 UTC, NulleanAndRain commented on Task 2/Task_2/FigureBuilder.cs
> +            Point location = InputPointRequestUntilItIsCorrect("Введите координаты точки расположения");
не очевидно какую именно точку надо указать
одну из вершин? центр?

2022-01-24 10:24 UTC, NulleanAndRain commented on Task 2/Task_2/FigureBuilder.cs
> +            Point location = InputPointRequestUntilItIsCorrect("Введите координаты точки расположения");
здесь то же самое, что в и CreateRectangle

2022-01-24 10:27 UTC, NulleanAndRain commented on Task 2/Task_2/FigureBuilder.cs
> +        public static Point InputPointRequestUntilItIsCorrect(string message)
название метода как-то излишне длинное, можно сократить, например, до GetPontInput, но в целом название отражает, что метод делает

2022-01-24 10:37 UTC, NulleanAndRain commented on Task 2/Task_2/Figures/Figure.cs
> +        public virtual double Length => 0;
лучше назвать это свойство Perimeter (но тогда может быть неочевидно, что ожидать от этого свойства в классе линии)

2022-01-24 10:53 UTC, NulleanAndRain commented on Task 2/Task_2/FigureBuilder.cs
> +        public static Point InputPointRequestUntilItIsCorrect(string message)
стоило сделать свою структуру Point. а не использовать готовую из System.Drawing

2022-01-24 10:54 UTC, NulleanAndRain commented on Task 2/Task_2/Figures/Line.cs
> +            Math.Sqrt(Math.Pow(second.X - first.X, 2) - Math.Pow(second.Y - first.Y, 2));
можно было бы вынести поиск расстояния между точками в отдельный метод в классе/структуре Point
к тому же можно получить NaN если разница по Y окажется больше, чем по X

2022-01-24 10:57 UTC, NulleanAndRain commented on Task 2/Task_2/Figures/Ring.cs
> +        public override double Area => Math.PI * (_external.Radius - _internal.Radius);
радиусы должны быть в квадрате
для очевидности лучше было бы возвращать _external.Area - _internal.Area

2022-01-24 10:57 UTC, NulleanAndRain commented on Task 2/Task_2/Figures/Ring.cs
> +        public Ring(Point center, double externalRadius, double internalRadius)
а что если внутренний радиус окажется больше внешнего?

2022-01-24 10:58 UTC, NulleanAndRain commented on Task 2/Task_2/Figures/Square.cs
> +    public class Square : Rectangle
нужен ли для квадрата отдельный класс, если это частный случай прямоугольника?

2022-01-24 11:03 UTC, NulleanAndRain commented on Task 2/Task_2/GraphicEditor.cs
> +                while (input is not Actions.ChangeUser)
здесь лучше сравнивать с Actions.Exit

2022-01-24 11:04 UTC, NulleanAndRain commented on Task 2/Task_2/GraphicEditor.cs
> +                        case Actions.None:
пропущен break

2022-01-24 11:11 UTC, NulleanAndRain requested changes
Критичные ошибки поправить (площадь кольца, нет своего Point), остальные можно по желанию в качестве практики

2022-01-25 15:27 UTC, UltimateEscanor commented on Task 2/String/CharacterString.cs
> +        public static CharacterString ToCharacterString(char[] symbols) => new CharacterString(symbols);
Удалён

2022-01-26 13:07 UTC, UltimateEscanor commented on Task 2/Task_2/GraphicEditor.cs
> +                        case Actions.None:
case Actions.None опускается ниже к реализации следующего case, реализации Actions.Exit и Actions.ChangeUser кроме break; на уровне switch нет.

2022-01-26 13:08 UTC, UltimateEscanor commented on Task 2/Task_2/Figures/Line.cs
> +            Math.Sqrt(Math.Pow(second.X - first.X, 2) - Math.Pow(second.Y - first.Y, 2));
Добавил структуру Point и перенёс туда метод, баг пофиксил

2022-01-26 13:09 UTC, UltimateEscanor commented on Task 2/Task_2/Figures/Ring.cs
> +        public override double Area => Math.PI * (_external.Radius - _internal.Radius);
Сделал очевиднее

2022-01-26 13:10 UTC, UltimateEscanor commented on Task 2/Task_2/Figures/Ring.cs
> +        public Ring(Point center, double externalRadius, double internalRadius)
Добавил проброс ошибки в конструкторе, если есть такая попытка, так же в самом методе создания кольца добавил проверку

2022-01-26 13:12 UTC, UltimateEscanor commented on Task 2/Task_2/Figures/Square.cs
> +    public class Square : Rectangle
На сколько я понял квадрат не должен наследоваться от прямоугольника, из-за их разности в полях и возможных проблемах при изменении размеров сторон. С точки зрения ООП нельзя квадратом наследоваться от прямоугольника.

2022-01-26 13:13 UTC, UltimateEscanor commented on Task 2/Task_2/Figures/Square.cs
> +    public class Square : Rectangle
Реализация квадрата была изменена

2022-02-03 09:09 UTC, NulleanAndRain commented on Task 2/Task_2/FigureBuilder.cs
> +    public class FigureBuilder
все же это factory
https://stackoverflow.com/questions/757743/what-is-the-difference-between-builder-design-pattern-and-factory-design-pattern

2022-02-03 09:22 UTC, NulleanAndRain approved these changes

2022-02-03 14:14 UTC, merged